---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: wp
  labels:
    app: wp
spec:
  selector:
    app: wp
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
# Assume GKE ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: wp
            port:
              number: 80
